Since Model A has the best test accuracy (0.86), we will use it to make predictions on judge.csv

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving judge.csv to judge.csv


In [ ]:
judge_cust_df = pd.read_csv('dataset.csv', delimiter=',')

In [ ]:
customer_ids= judge_cust_df['CustomerId'].to_numpy()

In [ ]:
customer_ids

array([15647572, 15797692, 15713559, ..., 15700549, 15704081, 15767729])

In [ ]:
judge_cust_df= judge_cust_df.drop(columns=['CustomerId', 'Surname'])

In [ ]:
judge_cust_df= handle_string_type_columns(judge_cust_df)

In [ ]:
judge_cust_df

CreditScore Geography Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             504         0      0  ...               1        136909.88       0
1             659         1      1  ...               0        136540.09       0
2             473         2      1  ...               1         72946.95       0
3             637         0      1  ...               1        181610.60       0
4             657         0      0  ...               1         91673.60       0
...           ...       ...    ...  ...             ...              ...     ...
8995          754         1      1  ...               0        144134.64       0
8996          709         2      0  ...               1        134732.99       0
8997          721         1      0  ...               1          4493.12       0
8998          595         2      0  ...               1         57862.88       0
8999          646         0      0  ...               1         42537.59       1

[9000 rows x 11 columns]

In [ ]:
Judge_Y= judge_cust_df["Exited"].to_numpy()

In [ ]:
Judge_Y

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
Judge_X = judge_cust_df.drop(columns=['Exited']).to_numpy()

In [ ]:
Judge_X

array([[504, 0, 0, ..., 1, 1, 136909.88],
       [659, 1, 1, ..., 1, 0, 136540.09],
       [473, 2, 1, ..., 1, 1, 72946.95],
       ...,
       [721, 1, 0, ..., 1, 1, 4493.12],
       [595, 2, 0, ..., 1, 1, 57862.88],
       [646, 0, 0, ..., 1, 1, 42537.59]], dtype=object)

In [ ]:
Judge_X_np = np.asarray(Judge_X).astype('float32')

In [ ]:
model_A.predict(Judge_X_np)

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [ ]:
import csv

csvfile= open("judge_pred.csv", 'w')

csvwriter = csv.writer(csvfile)  



In [ ]:
final_output_to_write= list()

customer_counter=0
for row in Judge_X:
  row_np = np.asarray(row).astype('float32')
  #print(row_np)
  row_np= tf.expand_dims(row_np, axis=0)
  CustomerId= customer_ids[customer_counter]
  pred= model_A(row_np).numpy()[0][0]
  print(pred)

  final_output_to_write.append([CustomerId,pred ])
  customer_counter+=1

Streaming output truncated to the last 5000 lines.
1.0
0.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
0.0
1.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
0.0
0.0
1.0
0.0
1.0
0.0
0.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
0.0
1.0
0.0
1.0
1.0
0.0
0.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
0.0
1.0
0.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0
1.0
1.0
0.0
1.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0
1.0
1.0
0.0
0.0
0.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
1.0
1.0
0.0
0.0
0.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
0.0
1.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
0.0
1.0
0.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
0

In [ ]:
csvwriter.writerow(["CustomerId", "Exited"])

19

In [ ]:
csvwriter.writerows(final_output_to_write)